version: '3'

services:
  registry:
    image: registry:2
    ports: ["5000:5000"]

  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse:4.2.1
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL
    - CONCOURSE_ADD_LOCAL_USER=admin:admin,docker:docker
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin
    - CONCOURSE_VAULT_URL=http://vault:8200
    - CONCOURSE_VAULT_AUTH_BACKEND=cert
    - CONCOURSE_VAULT_CLIENT_TOKEN=root

  vault:
    image: vault
    cap_add: [IPC_LOCK]
    ports: ["8200:8200"]
    command: server -dev -dev-root-token-id="root"
